// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcwzwftezqkbamqjdgiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjd3p3ZnRlenFrYmFtcWpkZ2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjA1MTIsImV4cCI6MjA3MTQzNjUxMn0.nFqjPYKeQzrPFg1RIWyz0ymSGcNhtYQvdn00PlqBzwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});